### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './data/img_align_celeba.zip'

### ISSUE THREAD

**Issue by FBen3** [dmonn/dcgan-oreilly#1]
Hi, I'm having trouble with the `helper` function. Basically I copied the code and saved the .py file and manually imported it. However, I get the error mentioned in the title. 

<img width="1004" alt="screen shot 2018-02-24 at 02 57 45" src="https://user-images.githubusercontent.com/15108826/36624961-a461a660-190e-11e8-8ad5-961d272571db.png">

What am I doing wrong? 

Thanks

**Comment by swatishr** [comment]
create data folder manually in the current directory

**Comment by FBen3** [comment]
Thank you.
